# Configuración adicional para deployment en Kubernetes con observabilidad completa

apiVersion: v1
kind: Secret
metadata:
  name: backend-env-secrets
  namespace: cuenly-backend
type: Opaque
stringData:
  # Variables de Firebase (reemplaza con tus valores reales)
  FIREBASE_PROJECT_ID: "cuenly-app"
  FIREBASE_WEB_API_KEY: "tu-firebase-api-key"
  FIREBASE_SERVICE_ACCOUNT_KEY: |
    {
      "type": "service_account",
      "project_id": "cuenly-app",
      "private_key_id": "...",
      "private_key": "...",
      "client_email": "...",
      "client_id": "...",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token"
    }
  
  # API Keys
  frontend-api-key: "cuenly-frontend-dev-key-2025"
  openai-api-key: "tu-openai-api-key"
  
  # Base de datos
  MONGO_URI: "mongodb://mongodb-service:27017/cuenly"
  MONGO_DATABASE: "cuenly"
  
  # Configuración de observabilidad
  LOG_LEVEL: "INFO"
  OBSERVABILITY_ENABLED: "true"
  METRICS_ENABLED: "true"

---
# ConfigMap para configuración no sensible
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cuenly-backend
data:
  # Configuración de la aplicación
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  TEMP_PDF_DIR: "/tmp/cuenly/pdfs"
  LOG_FORMAT: "json"
  
  # Timeouts y límites
  REQUEST_TIMEOUT: "300"
  MAX_FILE_SIZE: "50MB"
  PROCESSING_TIMEOUT: "600"
  
  # Job scheduling
  JOB_INTERVAL_MINUTES: "60"
  MAX_CONCURRENT_JOBS: "2"